// filepath: src/weather/country-capitals.ts
export const countryToCapital: Record<string, string> = {
  nigeria: 'Abuja',
  usa: 'Washington',
  uk: 'London',
  france: 'Paris',
  japan: 'Tokyo',
  egypt: 'Cairo',
  brazil: 'Brasilia',
  russia: 'Moscow',
  china: 'Beijing',
  australia: 'Canberra',
  germany: 'Berlin',
  india: 'New Delhi',
  canada: 'Ottawa',
  italy: 'Rome',
  spain: 'Madrid',
  southafrica: 'Pretoria',
  kenya: 'Nairobi',
  mexico: 'Mexico City',
  argentina: 'Buenos Aires',
  indonesia: 'Jakarta',
  turkey: 'Ankara',
  saudiarabia: 'Riyadh',
  netherlands: 'Amsterdam',
  sweden: 'Stockholm',
  norway: 'Oslo',
  poland: 'Warsaw',
  ghana: 'Accra',
  ethiopia: 'Addis Ababa',
  singapore: 'Singapore',
  malaysia: 'Kuala Lumpur',
  thailand: 'Bangkok',
  uae: 'Abu Dhabi',
  israel: 'Jerusalem',
  switzerland: 'Bern',
  belgium: 'Brussels',
  austria: 'Vienna',
  greece: 'Athens',
  portugal: 'Lisbon',
  finland: 'Helsinki',
  ireland: 'Dublin',
  denmark: 'Copenhagen',
  newzealand: 'Wellington',
  southkorea: 'Seoul',
  pakistan: 'Islamabad',
  bangladesh: 'Dhaka',
  philippines: 'Manila',
  colombia: 'Bogotá',
  chile: 'Santiago',
  peru: 'Lima',
  venezuela: 'Caracas',
  morocco: 'Rabat',
  algeria: 'Algiers',
  tanzania: 'Dodoma',
  uganda: 'Kampala',
  sudan: 'Khartoum',
  angola: 'Luanda',
  zambia: 'Lusaka',
  zimbabwe: 'Harare',
  cameroon: 'Yaoundé',
  senegal: 'Dakar',
  ivorycoast: 'Yamoussoukro',
  tunisia: 'Tunis',
  libya: 'Tripoli',
  botswana: 'Gaborone',
  namibia: 'Windhoek',
  malawi: 'Lilongwe',
  mozambique: 'Maputo',
  madagascar: 'Antananarivo',
  drc: 'Kinshasa',
  congo: 'Brazzaville',
  gabon: 'Libreville',
  rwanda: 'Kigali',
  burundi: 'Gitega',
  sierra_leone: 'Freetown',
  liberia: 'Monrovia',
  mauritius: 'Port Louis',
  seychelles: 'Victoria',
  lesotho: 'Maseru',
  eswatini: 'Mbabane',
  somalia: 'Mogadishu',
  eritrea: 'Asmara',
  djibouti: 'Djibouti',
  centralafricanrepublic: 'Bangui',
  chad: 'N’Djamena',
  niger: 'Niamey',
  burkinafaso: 'Ouagadougou',
  benin: 'Porto-Novo',
  togo: 'Lomé',
  mali: 'Bamako',
  guinea: 'Conakry',
  gambia: 'Banjul',
  guinea_bissau: 'Bissau',
  cape_verde: 'Praia',
  southsudan: 'Juba',
  mauritania: 'Nouakchott',
  comoros: 'Moroni',
};
